global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['eduops-postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['eduops-redis:6379']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['eduops-api:5000']
    metrics_path: '/metrics'
